/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.JDialog;

/**
 *
 * @author stefan.kujovic
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuPerson = new javax.swing.JMenu();
        itemAdd = new javax.swing.JMenuItem();
        itemTable = new javax.swing.JMenuItem();
        itemComboBox = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPerson.setText("Person");

        itemAdd.setText("Add");
        itemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddActionPerformed(evt);
            }
        });
        menuPerson.add(itemAdd);

        itemTable.setText("Show in Table");
        itemTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTableActionPerformed(evt);
            }
        });
        menuPerson.add(itemTable);

        itemComboBox.setText("Show in ComboBox");
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });
        menuPerson.add(itemComboBox);

        menuBar.add(menuPerson);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        MyView showInComboBoxDialog = new ShowPersonComboBox(this, false);
        Controller.getInstance().registerView(showInComboBoxDialog);
        ((JDialog) showInComboBoxDialog).setVisible(true);
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void itemTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTableActionPerformed
        MyView showInTableDialog = new ShowPersonTable(this, false);
        Controller.getInstance().registerView(showInTableDialog);
        ((JDialog) showInTableDialog).setVisible(true);
    }//GEN-LAST:event_itemTableActionPerformed

    private void itemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddActionPerformed
        (new AddPersonDialog(this, false)).setVisible(true);
    }//GEN-LAST:event_itemAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAdd;
    private javax.swing.JMenuItem itemComboBox;
    private javax.swing.JMenuItem itemTable;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPerson;
    // End of variables declaration//GEN-END:variables
}
