/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Controller;
import domain.Person;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author stefan.kujovic
 */
public class ShowPersonComboBox extends javax.swing.JDialog implements MyView {

    /**
     * Creates new form ShowPersonComboBox
     */
    public ShowPersonComboBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //showPersons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPersons = new javax.swing.JComboBox<>();
        lblPerson = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPersonsActionPerformed(evt);
            }
        });

        lblPerson.setText("Person:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(lblPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPersons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerson))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPersonsActionPerformed
        Person person = (Person) cbPersons.getSelectedItem();
        int selectedIndex = cbPersons.getSelectedIndex();
        
        Controller.getInstance().setSelectedIndex(selectedIndex);
        
    }//GEN-LAST:event_cbPersonsActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Person> cbPersons;
    private javax.swing.JLabel lblPerson;
    // End of variables declaration//GEN-END:variables

    private void showPersons() {
        Person[] persons = controller.Controller.getInstance().getAllPerson().toArray(size -> new Person[size]);
        cbPersons.setModel(new DefaultComboBoxModel<>(persons));
    }

    @Override
    public void update() {
        showPersons();
    }

   
    public void setSelectedIndex(int selectedIndex) {
        cbPersons.setSelectedIndex(selectedIndex);
    }
}
